#!/usr/bin/env python3
"""Translate all quest content in quests_zh.json to Chinese."""
import json, copy, re

with open('src/data/zh/quests_zh.json', 'r') as f:
    data = json.load(f)

# ═══════════════════════════════════════════════════════════════
# QUEST NAME TRANSLATIONS
# ═══════════════════════════════════════════════════════════════
QUEST_NAMES = {
    "Trash Into Treasure": "变废为宝",
    "Off The Radar": "脱离雷达",
    "Safe Passage": "安全通道",
    "What Goes Around": "因果循环",
    "Sparks Fly": "火花飞溅",
    "The Right Tool": "正确的工具",
    "Greasing Her Palms": "打点关系",
    "Hatch Repairs": "舱口修理",
    "Down To Earth": "脚踏实地",
    "The Trifecta": "三连胜",
    "Doctor's Orders": "医嘱",
    "Medical Merchandise": "医疗商品",
    "A Reveal In Ruins": "废墟中的发现",
    "Eyes In The Sky": "天空之眼",
    "After Rain Comes": "雨后天晴",
    "Untended Garden": "无人照料的花园",
    "The Root Of The Matter": "根源之谜",
    "Water Troubles": "水源问题",
    "Source Of The Contamination": "污染源头",
    "Switching The Supply": "切换供给",
    "A Warm Place To Rest": "温暖的休息之地",
    "Prescriptions Of The Past": "过去的处方",
    "Power Out": "断电",
    "Flickering Threat": "闪烁的威胁",
    "Bees!": "蜜蜂！",
    "Espresso": "浓缩咖啡",
    "Life Of A Pharmacist": "药剂师的生活",
    "Tribute To Toledo": "致敬托莱多",
    "Digging Up Dirt": "挖掘秘密",
    "Building A Library": "建造图书馆",
    "A New Type Of Plant": "新品种植物",
    "Armored Transports": "装甲运输",
    "Turnabout": "逆转",
    "Back On Top": "重回巅峰",
    "Our Presence Up There": "我们在上方的存在",
    "Lost In Transmission": "传输中丢失",
    "Communication Hideout": "通信藏身处",
    "Into The Fray": "投入战斗",
    "Dormant Barons": "沉睡的男爵",
    "What We Left Behind": "我们留下的",
    "Broken Monument": "破碎的纪念碑",
    "Mixed Signals": "混乱的信号",
    "Straight Record": "直接记录",
    "Keeping The Memory": "守护记忆",
    "Echoes Of Victory Ridge": "胜利山脊的回声",
    "Marked For Death": "死亡标记",
    "Market Correction": "市场纠正",
    "Eyes On The Prize": "目标明确",
    "Industrial Espionage": "工业间谍",
    "Unexpected Initiative": "意外的主动",
    "A Symbol Of Unification": "统一的象征",
    "Celeste's Journals": "Celeste的日记",
    "Out Of The Shadows": "走出阴影",
    "The Major's Footlocker": "少校的储物柜",
    "Paving The Way": "铺路",
    "Deciphering The Data": "破译数据",
    "Groundbreaking": "破土动工",
    "A Toxic Trail": "有毒的踪迹",
    "The Stench Of Corruption": "腐败的恶臭",
    "The Clean Dream": "清洁之梦",
    "Reduced To Rubble": "化为废墟",
    "With A Trace": "留下痕迹",
    "In My Image": "以我之形",
    "Snap And Salvage": "拍照与回收",
    "The League": "联盟",
    "Combat Recon": "战斗侦察",
    "Bombing Run": "轰炸行动",
    "On Deaf Ears": "充耳不闻",
    "On The Map": "登上地图",
    "With A View": "带风景的",
    "Movie Night": "电影之夜",
    "A Prime Specimen": "优质标本",
    "Stable Housing": "稳定住所",
    "Keeping An Eye Out": "保持警惕",
    "A Dead End": "死胡同",
    "A Rising Tide": "涨潮",
    "Making Do": "将就",
}

# ═══════════════════════════════════════════════════════════════
# LOCATION TRANSLATIONS
# ═══════════════════════════════════════════════════════════════
LOC_MAP = {
    "Dam Battlegrounds": "大坝战场",
    "Buried City": "埋葬之城",
    "Spaceport": "航天港",
    "The Blue Gate": "蓝门",
    "Blue Gate": "蓝门",
    "Stella Montis": "星山",
}

def translate_location(loc):
    if not loc:
        return loc
    parts = [p.strip() for p in loc.split(',')]
    translated_parts = [LOC_MAP.get(p, p) for p in parts]
    return ', '.join(translated_parts)

# ═══════════════════════════════════════════════════════════════
# UNLOCK REQUIREMENT TRANSLATIONS
# ═══════════════════════════════════════════════════════════════
UNLOCK_MAP = {
    "Blue Gate Unlocked (18 rounds played)": "蓝门已解锁（已完成18轮游戏）",
    "Stella Montis Unlocked (24 rounds played)": "星山已解锁（已完成24轮游戏）",
    "The Blue Gate Unlocked": "蓝门已解锁",
}

# ═══════════════════════════════════════════════════════════════
# REWARD NAME TRANSLATIONS
# ═══════════════════════════════════════════════════════════════
REWARD_NAMES = {
    "Adrenaline Shot": "肾上腺素注射",
    "Advanced Electrical Components": "高级电气元件",
    "Advanced Mechanical Components": "高级机械元件",
    "Air Freshener": "空气清新剂",
    "Angled Grip II": "斜握把 II",
    "Antiseptic": "消毒剂",
    "Anvil III": "铁砧 III",
    "Arpeggio I": "琶音 I",
    "Aviator Outfit (Blue Yellow Color)": "飞行员服装（蓝黄颜色）",
    "Aviator Outfit (Crimson Racer Color)": "飞行员服装（深红赛车手颜色）",
    "Aviator Outfit (Dusted Cream Color)": "飞行员服装（灰奶油颜色）",
    "Backpack Attachment (Cans)": "背包挂件（罐子）",
    "Backpack Charm (Banana)": "背包挂件（香蕉）",
    "Backpack Charm (Burger Boy)": "背包挂件（汉堡男孩）",
    "Backpack Charm (Succulent)": "背包挂件（多肉植物）",
    "Barricade Kit": "路障工具",
    "Binoculars": "望远镜",
    "Blaze Grenade": "燃烧弹",
    "Blue Light Stick": "蓝色荧光棒",
    "Buried City Town Hall Key": "埋葬之城市政厅钥匙",
    "Cheer Emote": "欢呼表情",
    "Combat Mk. 2": "战斗型 Mk.2",
    "Complex Gun Parts": "复杂枪械零件",
    "Credits": "信用点",
    "Dam Control Center Tower Key": "大坝控制中心塔钥匙",
    "Deployable Cover": "可部署掩体",
    "Door Blocker": "门阻挡器",
    "Durable Cloth": "耐用布料",
    "Electrical Components": "电气元件",
    "Equalizer": "均衡者",
    "Extended Medium Mag I": "扩展中型弹匣 I",
    "Frag Grenade": "碎片手雷",
    "Guitar": "吉他",
    "Heavy Ammo": "重型弹药",
    "Heavy Gun Parts": "重型枪械零件",
    "Herbal Bandage": "草药绷带",
    "Hiker Outfit (Black Color)": "徒步者服装（黑色）",
    "Il Toro IV": "公牛 IV",
    "Jupiter": "木星",
    "Launcher Ammo": "发射器弹药",
    "Light Ammo": "轻型弹药",
    "Light Gun Parts": "轻型枪械零件",
    "Looting MK. 3 (Safekeeper)": "拾取型 Mk.3（保管者）",
    "Looting Mk. 1": "拾取型 Mk.1",
    "Lure Grenade": "诱饵手雷",
    "Mastery Medal (Backpack Charm)": "精通奖章（背包挂件）",
    "Mechanical Components": "机械元件",
    "Med Kit": "医疗包",
    "Medium Ammo": "中型弹药",
    "Medium Gun Parts": "中型枪械零件",
    "Noisemaker": "噪音发生器",
    "Orange Camo (Origin Outfit)": "橙色迷彩（原始服装）",
    "Padlock": "挂锁",
    "Photoelectric Cloak": "光电隐身斗篷",
    "Portable Radar": "便携雷达",
    "Radio Renegade (Outfit)": "无线电叛逆（服装）",
    "Radio Renegade Bag Variant": "无线电叛逆背包变体",
    "Radio Renegade Goggles Variant": "无线电叛逆护目镜变体",
    "Radio Renegade Helmet Variant": "无线电叛逆头盔变体",
    "Rattler III": "响尾蛇 III",
    "Recorder": "竖笛",
    "Remote Raider Flare": "遥控掠夺者信号弹",
    "Scrap Metal": "废金属",
    "Shield Recharger": "护盾充能器",
    "Shotgun Parts": "霰弹枪零件",
    "Simple Gun Parts": "简易枪械零件",
    "Smoke Grenade": "烟雾弹",
    "Snitch Scanner": "告密扫描仪",
    "Sterilized Bandage": "消毒绷带",
    "Stun Grenade": "眩晕手雷",
    "Surge Shield Recharger": "激涌护盾充能器",
    "Tactical MK. 3 (Revival)": "战术型 Mk.3（复活）",
    "Tactical Mk. 2": "战术型 Mk.2",
    "Tangerine (Warden Color)": "橘色（守望者颜色）",
    "Venator I": "猎人 I",
    "Vita Shot": "维生素注射",
    "Warden Outfit (Tangerine Color)": "守望者服装（橘色）",
    "Wires": "电线",
    "Zipline": "滑索",
    "Blueprint: Horizontal Grip": "蓝图：水平握把",
    "Blueprint: Launcher Ammo": "蓝图：发射器弹药",
    "Blueprint: Remote Raider Flare": "蓝图：遥控掠夺者信号弹",
    "Blueprint: Looting MK. 3 (Safekeeper)": "蓝图：拾取型 Mk.3（保管者）",
    "Blueprint: Tactical MK. 3 (Revival)": "蓝图：战术型 Mk.3（复活）",
    "Burletta Blueprint": "滑稽剧蓝图",
    "Burletta III": "滑稽剧 III",
    "Canister": "罐",
    "Coffee Pot": "咖啡壶",
    "Combat Mk. 1": "战斗型 Mk.1",
    "Compensator I": "补偿器 I",
    "Compensator II": "补偿器 II",
    "Crude Explosives": "粗制炸药",
    "Dam Control Tower Key": "大坝控制塔钥匙",
    "Dam Staff Room Key": "大坝员工休息室钥匙",
    "Dam Testing Annex Key": "大坝测试附楼钥匙",
    "Deadline": "死线",
    "Defibrillator": "除颤器",
    "Duct Tape": "管道胶带",
    "Exodus Modules": "出埃及记模块",
    "Explosive Compound": "爆炸化合物",
    "Explosive Mine": "爆炸地雷",
    "Extended Light Mag I": "扩展轻型弹匣 I",
    "Extended Light Mag II": "扩展轻型弹匣 II",
    "Extended Light Magazine I": "扩展轻型弹匣 I",
    "Extended Medium Mag II": "扩展中型弹匣 II",
    "Extended Shotgun Mag II": "扩展霰弹枪弹匣 II",
    "Faded Flush (Aviator Color)": "褪色（飞行员颜色）",
    "Finger Gun Single Shot Emote": "手指枪单发表情",
    "Firecracker": "鞭炮",
    "Fireworks Box": "烟花盒",
    "Gas Mine": "毒气地雷",
    "Green Light Stick": "绿色荧光棒",
    "Heavy Fuze Grenade": "重型引信手雷",
    "Heavy Shield": "重型护盾",
    "Hiker Backpack (Black Color)": "徒步者背包（黑色）",
    "Hullcracker Blueprint": "破壳者蓝图",
    "Il Toro I": "公牛 I",
    "Jolt Mine": "电击地雷",
    "Li'l Smoke Grenade": "小型烟雾弹",
    "Light Shield": "轻型护盾",
    "Looting Mk. 2": "拾取型 Mk.2",
    "Lure Grenade Blueprint": "诱饵手雷蓝图",
    "Magnet": "磁铁",
    "Magnetic Accelerator": "磁力加速器",
    "Medium Shield": "中型护盾",
    "Metal Parts": "金属零件",
    "Mod Components": "改装元件",
    "Music Box": "音乐盒",
    "Muzzle Brake II": "枪口制退器 II",
    "Navy Blue (Warden Color)": "海军蓝（守望者颜色）",
    "Oil": "油",
    "Origin Outfit (Orange Camo Color)": "原始服装（橙色迷彩颜色）",
    "Patrol Car Key": "巡逻车钥匙",
    "Power Rod": "电源棒",
    "Processor": "处理器",
    "Pulse Mine": "脉冲地雷",
    "Radio Renegade Outfit (Bag Variant)": "无线电叛逆服装（背包变体）",
    "Radio Renegade Outfit (Blue Color)": "无线电叛逆服装（蓝色）",
    "Radio Renegade Outfit (Goggles Variant)": "无线电叛逆服装（护目镜变体）",
    "Radio Renegade Outfit (Grey Color)": "无线电叛逆服装（灰色）",
    "Radio Renegade Outfit (Helmet Variant)": "无线电叛逆服装（头盔变体）",
    "Radio Renegade Outfit (Red Color)": "无线电叛逆服装（红色）",
    "Raider Hatch Key": "掠夺者舱口钥匙",
    "Raider Tokens": "掠夺者代币",
    "Renegade I": "叛逆者 I",
    "Rosary": "念珠",
    "Seeker Grenade": "追踪手雷",
    "Sensors": "传感器",
    "Shaker": "沙锤",
    "Shotgun Ammo": "霰弹枪弹药",
    "Shotgun Choke II": "霰弹枪收束器 II",
    "Showstopper": "惊鸿一击",
    "Shrapnel Grenade": "弹片手雷",
    "Silencer II": "消音器 II",
    "Snap Blast Grenade": "速爆手雷",
    "Snap Hook": "弹簧钩",
    "Spaceport Trench Tower Key": "航天港壕沟塔钥匙",
    "Speaker Component": "扬声器元件",
    "Stable Stock I": "稳定枪托 I",
    "Stable Stock II": "稳定枪托 II",
    "Stable Stock III": "稳定枪托 III",
    "Steel Spring": "钢弹簧",
    "Stitcher II": "缝合者 II",
    "Synthesized Fuel": "合成燃料",
    "Tactical Mk. 1": "战术型 Mk.1",
    "Tactical Mk. 3 (Healing)": "战术型 Mk.3（治疗）",
    "Tagging Grenade": "标记手雷",
    "Trailblazer": "开拓者",
    "Trigger 'Nade Blueprint": "遥控雷蓝图",
    "Vertical Grip II": "垂直握把 II",
    "Vita Spray": "维生素喷雾",
    "Vulcano III": "火山 III",
    "Warden Outfit (Blue Color)": "守望者服装（蓝色）",
    "Wolfpack": "狼群",
    "Yellow Light Stick": "黄色荧光棒",
}

# ═══════════════════════════════════════════════════════════════
# OBJECTIVE TRANSLATIONS
# ═══════════════════════════════════════════════════════════════
OBJ_MAP = {
    "Collect the reward": "领取奖励",
    "Follow the clues": "跟随线索",
    "Follow the red markers": "跟随红色标记",
    "Reach Victory Ridge": "到达胜利山脊",
    "Restore the power": "恢复电力",
    "Find a way through": "找到通路",
    "Find and flip the power switch": "找到并拨动电源开关",
    "Repair the Generator": "修理发电机",
    "Report findings to Celeste": "向Celeste汇报发现",
    "Sabotage the cache": "破坏武器库",
    "Install the fuse": "安装保险丝",
    "Gather basic crafting materials": "收集基础制作材料",
    "Get a Hornet Driver for Shani": "为Shani获取大黄蜂驱动器",
    "Get a Wasp Driver for Shani": "为Shani获取黄蜂驱动器",
    "Get a Snitch Scanner for Shani": "为Shani获取告密扫描仪",
    "Get a Power Rod for Celeste": "为Celeste获取电源棒",
    "Get the Espresso Machine Parts for Apollo": "为Apollo获取浓缩咖啡机零件",
    "Bring supplies to Tian Wen": "给天文带去补给",
    "Help Celeste secure supplies": "帮助Celeste确保补给",
    "Loot a Supply Drop": "搜刮一个补给空投",
    "Loot a Baron Husk": "搜刮一个男爵外壳",
    "Deploy into Stella Montis": "部署进入星山",
    "Scout the area around The Blue Gate": "侦察蓝门周边区域",
    "Reach Piazza Roma in Buried City": "到达埋葬之城的罗马广场",
    "Reach the Barren Clearing": "到达荒芜空地",
    "Reach the Checkpoint": "到达检查站",
    "Secure the area for Tian Wen": "为天文确保区域安全",
    "Destroy 2 Spotters": "摧毁2个观察者",
    "Destroy a Bombardier": "摧毁一个轰炸兵",
    "Destroy a Fireball": "摧毁一个火球",
    "Destroy a Hornet": "摧毁一个大黄蜂",
    "Destroy a Leaper": "摧毁一个跳跃者",
    "Destroy a Rocketeer": "摧毁一个火箭兵",
    "Destroy a Snitch": "摧毁一个告密者",
    "Destroy a Wasp": "摧毁一个黄蜂",
    "Destroy an ARC Surveyor": "摧毁一个ARC勘测者",
    "Destroy 2 ARC enemies using any explosive grenade": "使用任何爆炸手雷摧毁2个ARC敌人",
    "Destroy a Hornet with a Trigger 'Nade or Snap Blast Grenade": "使用遥控雷或速爆手雷摧毁一个大黄蜂",
    "Destroy any ARC using a Fireball Burner": "使用火球燃烧器摧毁任何ARC",
    "Disable the first power switch": "关闭第一个电源开关",
    "Disable the second power switch": "关闭第二个电源开关",
    "Disable the third power switch": "关闭第三个电源开关",
    "Enable the comms terminal near the Olive Grove": "启用橄榄林附近的通信终端",
    "Enable the power on the Generator": "启用发电机电源",
    "Enable the power via the power switch underneath the stairs": "通过楼梯下方的电源开关启用电源",
    "Enter the Power Generation Complex by The Dam": "进入大坝旁的发电综合设施",
    "Enter the locked room at Pilgrim's Peak": "进入朝圣者之巅的锁定房间",
    "Establish a connection from the terminal": "从终端建立连接",
    "Find the Generator Room": "找到发电机房",
    "Find the Ventilation Shaft": "找到通风管道",
    "Find missing battery cell": "找到丢失的电池单元",
    "Install the battery cell in the Generator": "将电池单元安装到发电机中",
    "Find and monitor any Filtration System in the tunnels": "在隧道中找到并监控任何过滤系统",
    "Find and turn the valve in the tunnels under Spaceport": "在航天港地下隧道中找到并转动阀门",
    "Find and photograph the blueprints in the bunker": "在地堡中找到并拍摄蓝图",
    "Find and unlock the rear door of an armored patrol car": "找到并打开装甲巡逻车的后门",
    "Find and search 3 Androids": "找到并搜索3个人形机器人",
    "Find any sign of the missing engineer": "找到失踪工程师的任何迹象",
    "Find signs of who brought down the ARC machines": "找到是谁击落了ARC机器的线索",
    "Find the Arbusto Farmacia by the collapsed highway": "在塌陷高速公路旁找到Arbusto药房",
    "Find the building pictured on the whiteboard": "找到白板上图片中的建筑",
    "Find the container covered in tarp, and mark it": "找到帆布覆盖的集装箱并标记",
    "Find the flooded solar panels nearby the Grandioso Apartments": "在Grandioso公寓附近找到被淹的太阳能板",
    "Find the old EMP trap": "找到旧的EMP陷阱",
    "Find the printed shipping logs in the Assembly Workshops": "在组装车间找到打印的运输日志",
    "Find the shipping notes in the foreman's office": "在工头办公室找到运输单据",
    "Find the staff locker room": "找到员工更衣室",
    "Find the intake to the District's Water Supply": "找到区域供水系统的进水口",
    "Find the secluded roof terrace south-west of the Southern Station, look for blue tarps": "在南站西南找到隐蔽的屋顶露台，寻找蓝色帆布",
    "Find the researcher's flat and search for any research data": "找到研究员的公寓并搜索研究数据",
    "Find the researcher's guest logs on the reception computers": "在前台电脑上找到研究员的宾客记录",
    "Find where the researcher held their lecture, and access their notes": "找到研究员举办讲座的地方并查看笔记",
    "Find information about the prototypes on the Medical Research computers": "在医学研究电脑上查找原型信息",
    "Search for a notice board with a note from the researcher": "搜寻有研究员留言的告示板",
    "Follow the trail of destruction through the Broken Earth": "沿着破碎大地的破坏痕迹前进",
    "Interact with a nearby computer to help identify the correct paths": "使用附近电脑帮助识别正确路径",
    "Interact with any ARC Deforester": "与任何ARC伐木机互动",
    "Loot an ARC Deforester": "搜刮一个ARC伐木机",
    "Investigate any suspicious objects": "调查任何可疑物品",
    "Investigate the dead end at The Blue Gate": "调查蓝门的死胡同",
    "Investigate the rising tide in the area": "调查该区域的涨潮",
    "Investigate the unknown ARC machines": "调查未知的ARC机器",
    "Inspect the Adorned Wreckage": "检查装饰过的残骸",
    "Inspect the communications device": "检查通讯设备",
    "Inspect the grave": "检查坟墓",
    "Boot the antenna terminal near the Red Tower": "启动红塔附近的天线终端",
    "Complete the antenna installation on the roof": "完成屋顶天线安装",
    "Repair the antenna on the roof of the Field Depot": "修理野战仓库屋顶的天线",
    "Access the data archive in one of the domes": "访问其中一个穹顶中的数据档案",
    "Hoist the flag on the small platform overlooking the Red Lake": "在俯瞰红湖的小平台上升旗",
    "Locate the flag at Formicai Outpost": "在蚁穴前哨站找到旗帜",
    "Plant a bug on the weapon cache": "在武器库中安装窃听器",
    "Photograph the abounded housing project": "拍摄废弃住房项目",
    "Stabilize the observation deck near the Ridgeline": "稳定山脊线附近的观察台",
    "Shut down the EMP trap": "关闭EMP陷阱",
    "Reach the tunnels below the Spaceport": "到达航天港下方的隧道",
    "Reach the top of Control Tower A6": "到达A6控制塔顶部",
    "Nail down the roof plates on the Raider structure near Trapper's Glade": "在猎人林地附近的掠夺者建筑上钉牢屋顶板",
    "Monitor the Purification System in the bunker": "监控地堡中的净化系统",
    "Locate Lab 1 on the upper floor above the reception": "在前台上方楼层找到1号实验室",
    "Locate and upload the blackmail files to Celeste": "找到勒索文件并上传给Celeste",
    "Locate the Abandoned Highway Camp": "找到废弃高速公路营地",
    "Locate the Dead Drop inside the courtyard": "在庭院中找到秘密传递点",
    "Locate the Santa Maria Houses in Old Town": "在老城区找到圣玛丽亚住宅",
    "Locate the scanners on the upper floor of Control Tower A6": "在A6控制塔上层找到扫描仪",
    "Find a stable location in Stella Montis": "在星山找到一个稳定的位置",
    "Repair the leaking hydraulic pipes near a Raider Hatch": "修理掠夺者舱口附近漏水的液压管道",
    "Repair the solar panels using 5 Wires and 2 Batteries": "使用5根电线和2个电池修理太阳能板",
    "Rewire the solar panel using 3 Wires": "使用3根电线重新接线太阳能板",
    "Return the helmet to the memorial": "将头盔归还纪念碑",
    "Return to the water intake below the Water Treatment Control building": "返回水处理控制大楼下方的进水口",
    "Rotate the satellite dishes on the church roof, north of the Data Vault": "旋转数据库北方教堂屋顶的卫星天线",
    "Request in a Supply Drop from a Call Station": "从呼叫站请求补给空投",
    "Retrieve the battle plans from the hideout under the broken highway": "从断裂高速公路下的藏身处取回作战计划",
    "Retrieve Celeste's Journals from the northern outpost overlooking the Red Lakes": "从俯瞰红湖的北方前哨取回Celeste的日记",
    "Upload the data to the computer terminal in any Field Depot": "将数据上传到任何野战仓库的电脑终端",
    "Use the Magnetic Decryptor in the Fuel Control Building": "在燃料控制大楼使用磁力解密器",
    "Use the Magnetic Decryptor on the top floor of the Arrival Building": "在到达大楼顶层使用磁力解密器",
    "Use the Rotary Encoder to activate the server switch": "使用旋转编码器激活服务器开关",
    "Use the key on any Flushing Terminal to override the bypass protocol": "在任何冲洗终端上使用钥匙覆盖绕行协议",
    "Visit any of the Control Rooms near the Assembly Line": "参观装配线附近的任何控制室",
    "Go to any ENELICA building": "前往任何ENELICA建筑",
    "Go to the Broken Earth": "前往破碎大地",
    "Go to the North Trench Tower": "前往北壕沟塔",
    "Transmit your location from the roof of the Container Storage building": "从集装箱仓库屋顶发送你的位置",
    "Head to the antenna near the Fuel Control, and transmit your location": "前往燃料控制附近的天线并发送你的位置",
    "Head to the cactus patch in the wall breach, and transmit your location": "前往墙壁缺口处的仙人掌丛并发送你的位置",
    "Head to where the Fuel Lines snapped, and transmit your location": "前往燃料管线断裂处并发送你的位置",
    "Obtain 1 Battery": "获取1个电池",
    "Obtain 1 Durable Cloth": "获取1块耐用布料",
    "Obtain 1 Great Mullein": "获取1株毛蕊花",
    "Obtain 1 Surveyor Vault": "获取1个勘测保险库",
    "Obtain 1 Syringe": "获取1个注射器",
    "Obtain 2 Antiseptic": "获取2个消毒剂",
    "Obtain 6 Wires": "获取6根电线",
    "Obtain a Leaper Pulse Unit": "获取一个跳跃者脉冲装置",
    "Obtain a Rocketeer Driver": "获取一个火箭兵驱动器",
    "Obtain a Rotary Encoder": "获取一个旋转编码器",
    "Deliver 1 LiDAR Scanners to Shani": "向Shani交付1个激光雷达扫描仪",
    "Deliver 2 Journals to Celeste": "向Celeste交付2本日记",
    "Deliver First Wave Compass to Tian Wen": "向天文交付第一波指南针",
    "Deliver First Wave Rations to Tian Wen": "向天文交付第一波口粮",
    "Deliver Major Aiva's Mementos to Tian Wen": "向天文交付Aiva少校的纪念品",
    "Deliver Major Aiva's Patch to Celeste": "向Celeste交付Aiva少校的臂章",
    "Deliver Nutrient Meter to Tian Wen": "向天文交付营养测量仪",
    "Deliver a Bicycle Pump for Apollo": "为Apollo交付一个自行车打气筒",
    "Deliver a Bombardier Cell to Shani": "向Shani交付一个轰炸兵电池",
    "Deliver a Deflated Football to Apollo": "为Apollo交付一个漏气的足球",
    "Deliver a Field Crate to a Supply Station": "将野战箱交付到补给站",
    "Deliver a Flow Controller to Tian Wen": "向天文交付一个流量控制器",
    "Deliver a Magnetron to Tian Wen": "向天文交付一个磁控管",
    "Deliver a Moisture Meter to Tian Wen": "向天文交付一个湿度计",
    "Deliver a Portable TV to Apollo": "为Apollo交付一台便携电视",
    "Deliver a Spotter Relay to Shani": "向Shani交付一个观察者中继器",
    "Deliver an Ion Sputter to Shani": "向Shani交付一个离子溅射器",
    "Deliver the Burletta to the rival weapon cache": "将滑稽剧交付到对手的武器库",
    "Deliver the ESR Analyzer to Lance": "向Lance交付ESR分析仪",
    "Deliver the Experimental Seed Sample to Celeste": "向Celeste交付实验种子样本",
    "Deliver the First Wave Tape to Tian Wen": "向天文交付第一波录音带",
    "Deliver the Possibly Toxic Plant to Lance": "向Lance交付可能有毒的植物",
    "Deliver the Stack Of Movie Tapes to Apollo": "向Apollo交付一叠电影录像带",
    "Find 1 adventure book": "找到1本冒险书",
    "Find 1 detective book": "找到1本侦探书",
    "Find 1 romance book": "找到1本爱情书",
    "Document the pharmacist's family": "记录药剂师的家庭",
    "Document the pharmacist's hobbies": "记录药剂师的爱好",
    "Document the pharmacist's skills": "记录药剂师的技能",
    "Document the pharmacist's taste": "记录药剂师的品味",
    "Find Tian Wen's weapon cache near the Gas Station in the Outskirts": "在郊区加油站附近找到天文的武器库",
    "Search for Tian Wen's cache near the Warehouses": "在仓库附近搜寻天文的隐藏点",
    "Scope out a cover spot in the Parking Garage staircases": "在停车场楼梯间勘查掩护点",
    "Scope out a cover spot in the attics around Main Street": "在大街周围的阁楼勘查掩护点",
    "Scope out a cover spot in the buses near Marano Park": "在马拉诺公园附近的公交车中勘查掩护点",
    "Search 3 containers in the Hospital in Buried City": "在埋葬之城医院搜索3个容器",
    "Search any J Kozma Ventures container": "搜索任何J Kozma Ventures集装箱",
    "Search for Moisture Meter on the rooftop of the Grandioso Apartments": "在Grandioso公寓屋顶搜寻湿度计",
    "Search for a Hatch Key near the Raider Hatch": "在掠夺者舱口附近搜寻舱口钥匙",
    "Search for a Nutrient Meter in the broken rooftop gardens at Piazza Roma": "在罗马广场破损的屋顶花园搜寻营养测量仪",
    "Search for a compass near the broken-down vehicles": "在抛锚车辆附近搜寻指南针",
    "Search for any signs of survivors": "搜寻任何幸存者的痕迹",
    "Search for any traces of the agricultural research project": "搜寻任何农业研究项目的痕迹",
    "Search for the Flood Spill Intake near the Swamp": "在沼泽附近搜寻防洪进水口",
    "Search for the missing helmet": "搜寻失踪的头盔",
    "Search for the old field rations in the Raider camp": "在掠夺者营地搜寻旧野战口粮",
    "Search for the records": "搜寻记录",
    "Search for the seed vault in the 'room with a great view'": "在'风景优美的房间'中搜寻种子库",
    "Search for the video tape near the cylindrical containers": "在圆柱形容器附近搜寻录像带",
    "Search the Guard huts for a Armored Patrol Key Card": "在警卫亭搜寻装甲巡逻钥匙卡",
    "Search the bee hives around the Olive Grove": "搜索橄榄林周围的蜂巢",
    "Search the papers in the Security Checkpoint room by the Lobby": "在大厅旁安检室搜索文件",
    "Search the room for any clues of the saboteur's identity": "在房间中搜索破坏者身份的线索",
    "Search the room for any construction research": "在房间中搜索建筑研究资料",
    "Search the swamp for traces of the barrel's origins": "在沼泽中搜索桶的来源痕迹",
    "Search the trunk for clues about the saboteur's identity": "在行李箱中搜索破坏者身份的线索",
    "Take a Photo of any of the Rovers in the Sandbox": "在沙坑中拍摄任何一辆探测车",
    "Take a photo of the barrel truck": "拍摄桶装卡车",
    "Take a photo of the collapsed Highway": "拍摄塌陷的高速公路",
    "Reach the Arrival Building in Spaceport": "到达航天港的到达大楼",
    "Reach the Su Durante Warehouses in the Outskirts in Buried City": "到达埋葬之城郊区的Su Durante仓库",
    "Reach the Traffic Tunnel near the Blue Gate Checkpoint": "到达蓝门检查站附近的交通隧道",
    "Reach the Water Treatment Building in The Dam": "到达大坝的水处理大楼",
    "Find the Medical Exam Room inside the Departure Building": "在出发大楼内找到医疗检查室",
    # "In One Round" objectives
    "In One Round: Find an espresso machine to salvage for spare parts": "单轮内：找到一台浓缩咖啡机回收备用零件",
    "In One Round: Find the Electrical Substation south of the Spaceport": "单轮内：找到航天港南部的变电站",
    "In One Round: Find the tunnels under the Spaceport": "单轮内：找到航天港地下隧道",
    "In One Round: Go to the Hydroponic Dome Complex": "单轮内：前往水培穹顶综合设施",
    "In One Round: Go to the Research & Administration building": "单轮内：前往研究与管理大楼",
    "In One Round: Go to the Research Building": "单轮内：前往研究大楼",
    "In One Round: Locate the Flood Access Tunnel under the Red Lake Balcony": "单轮内：找到红湖阳台下方的防洪通道",
    "In One Round: Locate the Library in the City Center": "单轮内：找到市中心的图书馆",
    "In One Round: Locate the cache near Marano Station": "单轮内：找到马拉诺站附近的隐藏点",
    "In One Round: Obtain 2 ARC Powercells": "单轮内：获取2个ARC能量电池",
    "In One Round: Reach Victory Ridge": "单轮内：到达胜利山脊",
    "In One Round: Reach the Formicai Outpost in Dam Battlegrounds": "单轮内：到达大坝战场的蚁穴前哨站",
    "In One Round: Reach the Grandioso Apartments in Buried City": "单轮内：到达埋葬之城的Grandioso公寓",
    "In One Round: Reach the Jiangsu Warehouse": "单轮内：到达江苏仓库",
    "In One Round: Reach the Olive Grove in Blue Gate": "单轮内：到达蓝门的橄榄林",
    "In One Round: Reach the Red Tower in Old Town": "单轮内：到达老城区的红塔",
    "In One Round: Reach the hallowed grounds by the Scrap Yard": "单轮内：到达废料场旁的圣地",
    "In One Round: Reach the southwest lobby of the Departure Building": "单轮内：到达出发大楼西南大厅",
    "In One Round: Reach the wreckage in the Formicai Hills": "单轮内：到达蚁穴山丘中的残骸",
    "In One Round: Retrieve Celeste's Journals from the South Swamp Outpost": "单轮内：从南沼泽前哨取回Celeste的日记",
    "In One Round: Search for Major Aiva's mementos in the apartments northwest of The Dam": "单轮内：在大坝西北方的公寓中搜寻Aiva少校的纪念品",
    "In One Round: Search for an ESR Analyzer inside any pharmacy in Buried City": "单轮内：在埋葬之城的任何药房搜寻ESR分析仪",
    "In One Round: Search for the new plant near the Baron Husk in the Old Battleground": "单轮内：在旧战场男爵外壳附近搜寻新植物",
    "In One Round: Visit Control Tower A6": "单轮内：参观A6控制塔",
    "In One Round: Visit a Field Depot": "单轮内：参观野战仓库",
    "In One Round: Visit the Departure Building in Spaceport": "单轮内：参观航天港的出发大楼",
    "In One Round: Visit the Pattern House in The Dam": "单轮内：参观大坝的模型屋",
    # "On X, ..." objectives
    "On Buried City, install a LiDAR Scanner on top of the Galleria sign": "在埋葬之城，将激光雷达扫描仪安装在Galleria标志顶部",
    "On Buried City, mark the building with the mural in the Buried Properties": "在埋葬之城，标记埋葬地产中有壁画的建筑",
    "On Buried City, photograph the football magazines in any kiosk": "在埋葬之城，在任何报刊亭拍摄足球杂志",
    "On Buried City, reach the top floor above the Convinio in Piazza Roma": "在埋葬之城，到达罗马广场Convinio上方的顶楼",
    "On Buried City, search 2 containers in the Raider Camp beneath the Parking Garage": "在埋葬之城，在停车场下方的掠夺者营地搜索2个容器",
    "On Buried City, visit the barricaded area on floor 6 of the Space Travel Building": "在埋葬之城，参观太空旅行大楼6层的路障区域",
    "On Dam Battlegrounds, install a LiDAR Scanner at the top of the Control Tower": "在大坝战场，在控制塔顶部安装激光雷达扫描仪",
    "On Dam Battlegrounds, mark the Pattern House": "在大坝战场，标记模型屋",
    "On Dam Battlegrounds, photograph the goal by the Water Towers": "在大坝战场，拍摄水塔旁的球门",
    "On Dam Battlegrounds, search 2 containers in the Research & Administration building's medical room": "在大坝战场，在研究与管理大楼的医疗室搜索2个容器",
    "On Dam Battlegrounds, search for anything significant in the South Swamp Outpost": "在大坝战场，在南沼泽前哨搜寻任何重要物品",
    "On Dam Battlegrounds, visit the Locked Room in the Water Treatment Control building": "在大坝战场，参观水处理控制大楼中的锁定房间",
    "On Spaceport, install a LiDAR Scanner at the Communications Tower": "在航天港，在通信塔安装激光雷达扫描仪",
    "On Spaceport, mark the South Trench Tower": "在航天港，标记南壕沟塔",
    "On Spaceport, scope out the rocket thrusters outside the Rocket Assembly": "在航天港，勘查火箭组装区外的火箭推进器",
    "On Spaceport, search 2 containers in the Departure Building's exam rooms": "在航天港，在出发大楼检查室搜索2个容器",
    "On Spaceport, search for anything significant in Bilguun's Hideout, next to the Container Storage": "在航天港，在集装箱仓库旁的Bilguun藏身处搜寻重要物品",
    "On Stella Montis, search the Cultural Archives for old movie tapes": "在星山，在文化档案馆搜寻旧电影录像带",
    "On The Blue Gate, mark the white lookout tower south of the Warehouse Complex": "在蓝门，标记仓库综合设施南方的白色瞭望塔",
    "On The Blue Gate, visit the Maintenance Bunker": "在蓝门，参观维护地堡",
    "On spaceport, search 4 containers in the underground tunnels": "在航天港，在地下隧道搜索4个容器",
}

# ═══════════════════════════════════════════════════════════════
# APPLY TRANSLATIONS
# ═══════════════════════════════════════════════════════════════
for q in data['quests']:
    # Name
    if q['name'] in QUEST_NAMES:
        q['name'] = QUEST_NAMES[q['name']]

    # Location
    q['location'] = translate_location(q.get('location', ''))

    # Unlock requirement
    if q.get('unlock_requirement') and q['unlock_requirement'] in UNLOCK_MAP:
        q['unlock_requirement'] = UNLOCK_MAP[q['unlock_requirement']]

    # Objectives
    new_objs = []
    for o in q.get('objectives', []):
        new_objs.append(OBJ_MAP.get(o, o))
    q['objectives'] = new_objs

    # Rewards
    for r in q.get('rewards', []):
        if r.get('name') and r['name'] in REWARD_NAMES:
            r['name'] = REWARD_NAMES[r['name']]

# Save
with open('src/data/zh/quests_zh.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Stats
quests = data['quests']
en_names = sum(1 for q in quests if not any('\u4e00' <= c <= '\u9fff' for c in q.get('name', '')))
en_obj = 0
total_obj = 0
for q in quests:
    for o in q.get('objectives', []):
        total_obj += 1
        if not any('\u4e00' <= c <= '\u9fff' for c in str(o)):
            en_obj += 1
en_loc = sum(1 for q in quests if q.get('location') and not any('\u4e00' <= c <= '\u9fff' for c in q['location']))
print(f"Quest names remaining English: {en_names}/{len(quests)}")
print(f"Objectives remaining English: {en_obj}/{total_obj}")
print(f"Locations remaining English: {en_loc}/{len(quests)}")

# Show remaining English objectives
if en_obj > 0:
    print("\n--- Remaining English objectives ---")
    for q in quests:
        for o in q.get('objectives', []):
            if not any('\u4e00' <= c <= '\u9fff' for c in str(o)):
                print(f"  [{q['name']}] {o}")
